name: 'OQuaRE metrics calculation module'
description: 'Calculates the metrics of ontology files in the given folder based on the metrics set by the OQuaRE framework'
inputs:
  ontology-folder:
    description: 'Folder which contains .owl files'
    required: true
    default: 'ontologies'
  contents-folder:
    description: 'Folder which will contain results and archives'
    default: 'OQuaRE'
  reasoner:
    description: 'Reasoner used by OQuaRE'
    required: true
    default: 'ELK'

runs: 
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install -r requirements.txt
      shell: bash

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v18
      with:
        files: |
          ${{ inputs.ontology-folder }}/*.owl
      
    - name: Run script
      run: ./om-script.sh
      shell: bash
      env:
        CONTENTS_FOLDER: ${{ inputs.contents-folder }}
        ONTOLOGY_FOLDER: ${{ inputs.ontology-folder }}
        REASONER: ${{ inputs.reasoner }}
        ANY_CHANGED: ${{ steps.changed-files.outputs.any_changed }}
        RENAMED_FILES: ${{ steps.changed-files.outputs.renamed_files }}
        ALL_CHANGED_FILES: ${{ stesp.changed-files.outputs.all_changed_files }}
      
    - name: Commit and push
      uses: EndBug/add-and-commit@v8

      
