on: 
  workflow_dispatch:
    branches: [ testing ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: OQuaRE-metrics-test
    steps:
      # To use this repository's private action
      # You need to check out the repo
      - uses: actions/checkout@v2
      # Configuration
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Delete contents folder
        id: delete-contents
        run: |
          rm -rf OQuaRE
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Module testing: delete contents folder"
          git push -u origin $GITHUB_REF
          SHA=$(git rev-parse HEAD)
          echo "::set-output name=commitid::$SHA" 
      
      - name: Initial OQuaRE run test
        uses: ./
        with:
          ontology-folders: ontologies ontologies/imports
          testing-ref: ${{ steps.delete-contents.outputs.commitid }}
          testing: "true"

      - name: Modify ontology file
        id: modify-ontology
        run: |
          git pull
          echo -e "\n" >> ontologies/imports/obi.owl
          git add .
          git commit -m "Module testing: Modify ontology file"
          git push -u origin $GITHUB_REF
          SHA=$(git rev-parse HEAD)
          echo "::set-output name=commitid::$SHA"

      - name: Basic OQuaRE run test
        uses: ./
        with:
          ontology-folders: ontologies ontologies/imports
          testing-ref: ${{ steps.modify-ontology.outputs.commitid }}
          testing: "true"

      - name: Clean modified file and rename
        id: clean-rename
        run: |
          git pull
          head -n -1 ontologies/imports/obi.owl > temp.txt
          mv temp.txt ontologies/imports/obi.owl
          mv ontologies/imports/obi.owl ontologies/imports/obi_renamed.owl
          git push -u origin $GITHUB_REF
          SHA=$(git rev-parse HEAD)
          echo "::set-output name=commitid::$SHA"

      - name: OQuaRE run - Renamed file
        uses: ./
        with:
          ontology-folders: ontologies ontologies/imports
          testing-ref: ${{ steps.clean-rename.outputs.commitid }}
          testing: "true"
      
      - name: Modify non-ontology file
        id: modify-non-ontology
        run: |
          git pull
          touch test-file
          echo "Test file" >> test-file
          git push -u origin $GITHUB_REF
          SHA=$(git rev-parse HEAD)
          echo "::set-output name=commitid::$SHA"
      
      - name: OQuaRE run - Non-ontology file modified
        uses: ./
        with:
          ontology-folders: ontologies ontologies/imports
          testing-ref: ${{ steps.modify-non-ontology.outputs.commitid }}
          testing: "true"
      
      - name: Deletion of ontology file
        id: ontology-deletion
        run: |
          git pull
          touch ontologies/imports/deleted_ontology.owl
          git add .
          git commit -m "Module testing: created new ontology"
          rm -f ontologies/imports/deleted_ontology.owl
          git add .
          git commit -m "Module testing: Deletion of ontology-file"
          git push -u origin $GITHUB_REF
          SHA=$(git rev-parse HEAD)
          echo "::set-output name=commitid::$SHA"

      - name: OQuaRE run - Deletion of ontology file
        uses: ./
        with:
          ontology-folders: ontologies ontologies/imports
          testing-ref: ${{ steps.ontology-deletion.outputs.commitid }}
          testing: "true"

      - name: Rename ontology back to original name
        id: rename-back
        run: |
          git pull
          mv ontologies/imports/obi_renamed.owl ontologies/imports/obi.owl
          git add .
          git commit -m "Module testing: renaming file to original name"
          git push -u origin $GITHUB_REF
          SHA=$(git rev-parse HEAD)
          echo "::set-output name=commitid::$SHA"
      
      - name: OQuaRE run - modified parameters
        uses: ./
        with:
          ontology-folders: ontologies ontologies/imports
          reasoner: HERMIT
          category-plots: "false"
          testing-ref: ${{ steps.rename-back.outputs.commitid }}
          testing: "true"

